// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbNGQUXLJr95pgnn8gPPz_6qNReVBBKXU',
    appId: '1:556553478901:web:487483d89d87ef4624dbbc',
    messagingSenderId: '556553478901',
    projectId: 'firestore-7b29a',
    authDomain: 'firestore-7b29a.firebaseapp.com',
    storageBucket: 'firestore-7b29a.firebasestorage.app',
    measurementId: 'G-5DWPT96JYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDudqPAP4u4Ed8Ow1ZWiWgy3ht83wjDa6I',
    appId: '1:556553478901:android:7c95fe542dad9a1e24dbbc',
    messagingSenderId: '556553478901',
    projectId: 'firestore-7b29a',
    storageBucket: 'firestore-7b29a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfYwAFmUtNd1lQORLX_XHw9ZWjSbUT-p0',
    appId: '1:556553478901:ios:b6b1563156cb010524dbbc',
    messagingSenderId: '556553478901',
    projectId: 'firestore-7b29a',
    storageBucket: 'firestore-7b29a.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfYwAFmUtNd1lQORLX_XHw9ZWjSbUT-p0',
    appId: '1:556553478901:ios:b6b1563156cb010524dbbc',
    messagingSenderId: '556553478901',
    projectId: 'firestore-7b29a',
    storageBucket: 'firestore-7b29a.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbNGQUXLJr95pgnn8gPPz_6qNReVBBKXU',
    appId: '1:556553478901:web:374b7868f61dc92024dbbc',
    messagingSenderId: '556553478901',
    projectId: 'firestore-7b29a',
    authDomain: 'firestore-7b29a.firebaseapp.com',
    storageBucket: 'firestore-7b29a.firebasestorage.app',
    measurementId: 'G-Z54KS9M8P0',
  );
}
